# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/xenial64"
    master.vm.box_check_update = false
    master.vm.network :private_network, ip: "192.168.33.10"
    master.vm.network "forwarded_port", guest: 6379, host: 46379
    master.vm.hostname = "master"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    master.vm.provision "shell", path: "provision.sh"
  end

  config.vm.define "slave1" do |slave1|
    slave1.vm.box = "ubuntu/xenial64"
    slave1.vm.box_check_update = false
    slave1.vm.network :private_network, ip: "192.168.33.11"
    slave1.vm.network "forwarded_port", guest: 6379, host: 46380
    slave1.vm.hostname = "slave1"
    slave1.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    slave1.vm.provision "shell", path: "provision.sh"
  end

  config.vm.define "slave2" do |slave2|
    slave2.vm.box = "ubuntu/xenial64"
    slave2.vm.box_check_update = false
    slave2.vm.network :private_network, ip: "192.168.33.12"
    slave2.vm.network "forwarded_port", guest: 6379, host: 46381
    slave2.vm.hostname = "slave2"
    slave2.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
    slave2.vm.provision "shell", path: "provision.sh"
  end

end
