# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "main" do |main|

    main.vm.box = "centos/7"
    main.vm.box_check_update = false

    main.vm.network :private_network, ip: "192.168.33.10"
    # main.vm.network "forwarded_port", guest: 80, host: 48080

    main.vm.synced_folder "./data", "/vagrant"

    main.vm.provider "virtualbox" do |vb|
      unless File.exist?('./anotherDisk.vdi')
        vb.customize ['createhd', '--filename', './anotherDisk.vdi', '--variant', 'Fixed', '--size', 10 * 1024]
      end
      vb.memory = "1024"
      vb.customize ['storageattach', :id,  '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', './anotherDisk.vdi']
    end

    main.vm.provision "shell", path: "mk_partitions.sh"
    main.vm.provision "shell", inline: <<-SHELL
    sudo yum install lvm2 -y
    echo "===== 创建物理卷 ====="
    sudo pvcreate /dev/sdb[1,2,3] # 创建 3 个物理卷
    sudo pvs                    # 查看
    echo "===== 将物理卷合成卷组 ====="
    sudo vgcreate myvg /dev/sdb1 /dev/sdb2 # 将其中 2 个物理卷合成卷组
    sudo pvs
    sudo vgs
    echo "====== 在卷组之上创建逻辑卷 ====="
    sudo lvcreate -L 1G -n mylv1 myvg # 在卷组之上创建逻辑卷
    sudo lvs
    sudo mkdir /mnt/mylv1
    sudo mkfs.ext4 /dev/myvg/mylv1
    sudo mount /dev/myvg/mylv1 /mnt/mylv1
    echo "===== 扩充容量 ====="
    sudo vgextend myvg /dev/sdb3 # 扩充卷组容量
    sudo lvextend -L +1G /dev/myvg/mylv1 # 扩充逻辑卷容量
    sudo lvs
    sudo df -h                  # 文件系统未反映新增的容量
    sudo resize2fs /dev/myvg/mylv1 # 通知文件系统更新容量
    sudo df -h
    SHELL
  end


end
