# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "main" do |main|

    main.vm.box = "ubuntu/xenial64"
    main.vm.box_check_update = false

    main.vm.network :private_network, ip: "192.168.33.10"
    main.vm.network "forwarded_port", guest: 6379, host: 46379

    main.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    main.vm.provision "shell", inline: <<-SHELL
    REDIS_VERSION=6.0.9
    apt-get update
    apt-get install make gcc pkg-config -y
    mkdir /opt/redis
    cd /opt/redis
    wget http://download.redis.io/releases/redis-$REDIS_VERSION.tar.gz
    tar xfvz redis-$REDIS_VERSION.tar.gz
    cd redis-$REDIS_VERSION
    make MALLOC=libc
    make install
    useradd redis
    mkdir -p /etc/redis
    mkdir -p /var/redis
    chown redis:redis /var/redis
    cp /vagrant/redis.conf /etc/redis/6379.conf
    cp /vagrant/redis.init.d /etc/init.d/redis_6379
    chmod a+x /etc/init.d/redis_6379
    update-rc.d redis_6379 defaults
    service redis-server start

    SHELL
  end


end
