# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"


Vagrant.configure(2) do |config|

  # config.vm.box = "centos/7"
  config.vm.box = "ubuntu/xenial64"

  config.vm.define "ansible-node1" do |config|
    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", 1024]
        v.customize ["modifyvm", :id, "--cpus", 1]
    end
    config.vm.network :private_network, ip: "192.168.200.11"
    config.vm.network "forwarded_port", guest: 22, host: 48011
  end


  config.vm.define "ansible-node2" do |config|
    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", 1024]
        v.customize ["modifyvm", :id, "--cpus", 1]
    end
    config.vm.network :private_network, ip: "192.168.200.12"
    config.vm.network "forwarded_port", guest: 22, host: 48012
  end

  config.vm.provision "shell", privileged: false, path: "./setup.sh"
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end