api_version: extensions/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.7.9
        name: nginx
        ports:
        - container_port: 80
