apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-pref
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: frontend-pref
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: backend
      containers:
      - name: main
        image: busybox
        args:
        - sleep
        - "99999"
