# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-8"
  config.ssh.forward_agent = true # So that boxes don't have to setup key-less ssh
  config.ssh.insert_key = false # To generate a new ssh key and don't use the default Vagrant one

  vars = {
     "TEST" => "ARP"
  }

  # escape environment variables to be loaded to /etc/profile.d/
  as_str = vars.map{|k,str| ["export #{k}=#{str.gsub '$', '\$'}"] }.join("\n")

  # common provisioning for all
  config.vm.provision "shell", inline: "echo \"#{as_str}\" > /etc/profile.d/arp_env.sh", run: "always"
  config.vm.provision "shell", path: "scripts/init.sh", env: vars

  config.vm.define "client" do |s|
    s.vm.hostname = "client"
    s.vm.network "private_network", ip: "172.168.1.2"
    s.vm.network "private_network", ip: "10.74.68.10"
    s.vm.provision "shell", path: "scripts/client.sh", env: vars
  end

  config.vm.define "dut" do |s|
    s.vm.hostname = "dut"
    s.vm.network "private_network", ip: "172.168.1.3"
    s.vm.network "private_network", ip: "10.74.68.11"
    s.vm.provision "shell", path: "scripts/dut.sh", env: vars
  end


  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end
end
