# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7"
  config.ssh.forward_agent = true # So that boxes don't have to setup key-less ssh
  config.ssh.insert_key = false # To generate a new ssh key and don't use the default Vagrant one

  vars = {
     "TEST" => "TUN"
  }

  # escape environment variables to be loaded to /etc/profile.d/
  as_str = vars.map{|k,str| ["export #{k}=#{str.gsub '$', '\$'}"] }.join("\n")

  # common provisioning for all
  config.vm.provision "shell", inline: "echo \"#{as_str}\" > /etc/profile.d/tun_env.sh", run: "always"
  config.vm.provision "shell", path: "scripts/init.sh", env: vars

  config.vm.define "server" do |s|
    s.vm.hostname = "server"
    s.vm.network "private_network", ip: "10.74.68.100"
    s.vm.network "private_network", ip: "172.0.0.100", virtualbox__intnet: "server"
    s.vm.provision "shell", path: "scripts/server.sh", env: vars
  end

  config.vm.define "client" do |c|
    c.vm.hostname = "client"
    c.vm.network "private_network", ip: "10.74.68.10"
    c.vm.network "private_network", ip: "172.0.0.10", virtualbox__intnet: "client"
    c.vm.provision "shell", path: "scripts/client.sh", env: vars
  end


  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end
end
