# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # config.ssh.username = "vagrant"
  # config.ssh.password = "vagrant"
  config.vm.box = "ruanhao/redis"
  config.vm.box_version = "6.0.9"
  config.vm.box_check_update = false
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provider "virtualbox" do |vb|
    # vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.memory = 1024
    vb.cpus = 1
  end

  [1, 2, 3, 4].each do |index|
    config.vm.define "master#{index}" do |cfg|
      cfg.vm.network :private_network, ip: "192.168.33.#{10 + index}"
      cfg.vm.network "forwarded_port", guest: 6379, host: "#{46379 + index - 1}"
      cfg.vm.hostname = "master#{index}"
    end

    config.vm.define "slave#{index}" do |cfg|
      cfg.vm.network :private_network, ip: "192.168.33.#{20 + index}"
      cfg.vm.network "forwarded_port", guest: 6379, host: "#{46389 + index - 1}"
      cfg.vm.hostname = "slave#{index}"
    end
  end

end
