# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# 参考 https://github.com/carmstrong/multinode-glusterfs-vagrant

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  glusterfs_version = "7"
  # We setup three nodes to be gluster hosts, and one gluster client to mount the volume
  (1..3).each do |i|
    config.vm.define vm_name = "gluster-server-#{i}" do |config|
      config.vm.hostname = vm_name
      ip = "172.21.12.#{i+10}"
      config.vm.network :private_network, ip: ip
      config.vm.provision :shell, inline: <<-SHELL
        apt-get update && apt-get install -yq software-properties-common
        add-apt-repository ppa:gluster/glusterfs-#{glusterfs_version}
        apt-get update && apt-get install -yq glusterfs-server
        apt-get install -yq nfs-ganesha-gluster nfs-ganesha-vfs # ganesha 启用 NFS 时需要加载的模块
      SHELL
    end
  end
  config.vm.define vm_name = "gluster-client" do |config|
    config.vm.hostname = vm_name
    ip = "172.21.12.10"
    config.vm.network :private_network, ip: ip
    config.vm.provision :shell, inline: <<-SHELL
      apt-get update && apt-get install -yq software-properties-common
      add-apt-repository ppa:gluster/glusterfs-#{glusterfs_version}
      apt-get update && apt-get install -yq glusterfs-client nfs-common
    SHELL
  end
end