# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/centos-7"
  config.ssh.forward_agent = true # So that boxes don't have to setup key-less ssh
  config.ssh.insert_key = false # To generate a new ssh key and don't use the default Vagrant one

  vars = {
     "TEST" => "POD_NETWORK"
  }

  # escape environment variables to be loaded to /etc/profile.d/
  as_str = vars.map{|k,str| ["export #{k}=#{str.gsub '$', '\$'}"] }.join("\n")

  # common provisioning for all
  config.vm.provision "shell", inline: "echo \"#{as_str}\" > /etc/profile.d/env.sh", run: "always"
  config.vm.provision "shell", path: "scripts/init.sh", env: vars

  config.vm.define "host1" do |h|
    h.vm.hostname = "host1"
    h.vm.network "private_network", ip: "10.10.103.91"
    h.vm.provision "shell", path: "scripts/host1.sh", env: vars, run: "always"
  end

  config.vm.define "host2" do |h|
    h.vm.hostname = "host2"
    h.vm.network "private_network", ip: "10.10.103.92"
    h.vm.provision "shell", path: "scripts/host2.sh", env: vars, run:"always"
  end


  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end
end
